@urlbase=http://localhost:3000
@urlHealth={{urlbase}}/health
@urlUser={{urlbase}}/usuarios
@urlMateria={{urlbase}}/materias
@urlAlumnoMateria={{urlbase}}/alumno-materia
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiNjRmMTgzLWU0ZjQtNGU1Yi05YmRhLTZjNGUxYTQ4ZDA0YSIsInJvbCI6IkFMVU1OTyIsImlhdCI6MTc4Njc0Mjg2NywiZXhwIjoxNzg2NzUwMDY3fQ.2QStfCuKAYqeTbZwkTBXLott8mUQu8gNR5yvkggTjiY
### Health
GET {{urlHealth}}

###

### LOGIN

POST {{urlUser}}/login
Content-Type: application/json

{
  "email": "co@gmail.com",
  "password": "1234"
}

### Crear usuario
POST {{urlUser}}
Content-Type: application/json

{
  "nombre": "Coni ",
  "email": "co@gmail.com",
  "password": "1234",
  "rol": "ALUMNO"
}

###


###

### Obtener todos los usuarios
GET {{urlUser}}

###

### Obtener un usuario por ID
GET {{urlUser}}/e4e824bb-0094-4616-9bea-2769a60ebe0d

###

### Modificar usuario
PUT {{urlUser}}/e4e824bb-0094-4616-9bea-2769a60ebe0d
Content-Type: application/json

{
  "nombre": "Juan Pérez",
  "email": "juan@gmail.com",
  "rol": "PROFESOR"
}

###

### Eliminar usuario
DELETE {{urlUser}}/e4e824bb-0094-4616-9bea-2769a60ebe0d

###

### Crear materia
POST {{urlMateria}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Programacion",
  "profesor_id": "e4e824bb-0094-4616-9bea-2769a60ebe0d"
}

###

### Obtener materias
GET {{urlMateria}}

###

### Obtener una materia
GET {{urlMateria}}/0d1b2e32-a29c-422a-9528-df3f2f045b27
Authorization: Bearer {{token}}
###

### Actualizar materia
PUT {{urlMateria}}/0d1b2e32-a29c-422a-9528-df3f2f045b27
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Programacion II",
  "profesor_id": "e4e824bb-0094-4616-9bea-2769a60ebe0d"
}

###

### Eliminar materia
DELETE {{urlMateria}}/ID_DE_LA_MATERIA

### Inscribir alumno

POST {{urlbase}}/cursan
Content-Type: application/json

{
    "alumno_id":"20023c8d-1d71-461a-80f7-7b53cc79412e",
    "materia_id":"0d1b2e32-a29c-422a-9528-df3f2f045b27"
}
### Ver inscripciones

GET {{urlAlumnoMateria}}

### Materias que dicta un profesor

GET {{urlbase}}/dictan/e4e824bb-0094-4616-9bea-2769a60ebe0d

